image: atlassian/default-image:2

pipelines:
  branches:
    default:
      - step:
          name: Run tests
          caches:
            - node
          script:
            - export CI=true
            - npm install
            - npm test

    iss10:
      - step:
          name: Run tests
          caches:
            - node
          script:
            - export CI=true
            - npm install
            - npm test
      - step:
          name: Production build
          caches:
            - node
          script:
            - npm install
            - npm run-script build
          artifacts:
            - build/**
